### ISSUE TITLE
estimators.GPCCA.plot_macrostates() gives error for legend plotting

### ISSUE THREAD

**Issue by knollr** [theislab/cellrank#1108]
Dear CellRank team, really nice tool! 
I found a small error in the `estimators.GPCCA.plot_macrostates()` function while going through your "Computing Initial and Terminal States" tutorial. 

The error occurs when setting the cluster_key as type "str" in the utils.py script.
```
obs_vals = adata.obs[value_to_plot]
obs_vals.cat.categories = obs_vals.cat.categories.astype(str)
```

example
```
adata = cr.datasets.pancreas(kind="preprocessed-kernel")
vk = cr.kernels.VelocityKernel.from_adata(adata, key="T_fwd")
g = cr.estimators.GPCCA(vk)
g.fit(cluster_key="clusters", n_states=[4, 12])
g.plot_macrostates(which="all", discrete=True, legend_loc="right", s=100)
```

```pytb
╭─────────────────────────────────────── Traceback (most recent call last) ───────────────────────────────────────╮
│ in <module>:2                                                                                                   │
│                                                                                                                 │
│   1 g.fit(cluster_key="clusters", n_states=[4, 12])                                                             │
│ ❱ 2 g.plot_macrostates(which="all", discrete=True, legend_loc="right", s=100)                                   │
│   3                                                                                                             │
│                                                                                                                 │
│ c:\Users\Knollr\Documents\github_ehrapy\.venv\Lib\site-packages\cellrank\estimators\terminal_states\_term_state │
│ s_estimator.py:375 in plot_macrostates                                                                          │
│                                                                                                                 │
│   372 │   │   colors = obj.colors                                                                               │
│   373 │   │                                                                                                     │
│   374 │   │   if discrete:                                                                                      │
│ ❱ 375 │   │   │   return self._plot_discrete(                                                                   │
│   376 │   │   │   │   _data=data,                                                                               │
│   377 │   │   │   │   _colors=colors,                                                                           │
│   378 │   │   │   │   _title=name,                                                                              │
│                                                                                                                 │
│ c:\Users\Knollr\Documents\github_ehrapy\.venv\Lib\site-packages\cellrank\estimators\terminal_states\_term_state │
│ s_estimator.py:455 in _plot_discrete                                                                            │
│                                                                                                                 │
│   452 │   │   │   if isinstance(title, str):                                                                    │
│   453 │   │   │   │   title = [title]                                                                           │
│   454 │   │   │                                                                                                 │
│ ❱ 455 │   │   │   scv.pl.scatter(                                                                               │
│   456 │   │   │   │   self.adata,                                                                               │
│   457 │   │   │   │   color=color + keys,                                                                       │
│   458 │   │   │   │   title=color + title,                                                                      │
│                                                                                                                 │
│ c:\Users\Knollr\Documents\github_ehrapy\.venv\Lib\site-packages\scvelo\plotting\scatter.py:668 in scatter       │
│                                                                                                                 │
│   665 │   │   │   │   g_bool = groups_to_bool(adata, add_outline, color)                                        │
│   666 │   │   │   │   if not (add_outline is None or g_bool is None):                                           │
│   667 │   │   │   │   │   groups = add_outline                                                                  │
│ ❱ 668 │   │   │   │   set_legend(                                                                               │
│   669 │   │   │   │   │   adata,                                                                                │
│   670 │   │   │   │   │   ax,                                                                                   │
│   671 │   │   │   │   │   color,                                                                                │
│                                                                                                                 │
│ c:\Users\Knollr\Documents\github_ehrapy\.venv\Lib\site-packages\scvelo\plotting\utils.py:555 in set_legend      │
│                                                                                                                 │
│    552 │   if legend_fontoutline is None:                                                                       │
│    553 │   │   legend_fontoutline = 1                                                                           │
│    554 │   obs_vals = adata.obs[value_to_plot]                                                                  │
│ ❱  555 │   obs_vals.cat.categories = obs_vals.cat.categories.astype(str)                                        │
│    556 │   color_keys = adata.uns[f"{value_to_plot}_colors"]                                                    │
│    557 │   if isinstance(color_keys, dict):                                                                     │
│    558 │   │   color_keys = np.array([color_keys[c] for c in obs_vals.cat.categories])                          │
│                                                                                                                 │
│ c:\Users\Knollr\Documents\github_ehrapy\.venv\Lib\site-packages\pandas\core\base.py:178 in __setattr__          │
│                                                                                                                 │
│    175 │   │   │   or getattr(self, key, None) is not None                                                      │
│    176 │   │   ):                                                                                               │
│    177 │   │   │   raise AttributeError(f"You cannot add any new attribute '{key}'")                            │
│ ❱  178 │   │   object.__setattr__(self, key, value)                                                             │
│    179                                                                                                          │
│    180                                                                                                          │
│    181 class SelectionMixin(Generic[NDFrameT]):                                                                 │
│                                                                                                                 │
│ c:\Users\Knollr\Documents\github_ehrapy\.venv\Lib\site-packages\pandas\core\accessor.py:99 in _setter           │
│                                                                                                                 │
│    96 │   │   │   │   return self._delegate_property_get(name)                                                  │
│    97 │   │   │                                                                                                 │
│    98 │   │   │   def _setter(self, new_values):                                                                │
│ ❱  99 │   │   │   │   return self._delegate_property_set(name, new_values)                                      │
│   100 │   │   │                                                                                                 │
│   101 │   │   │   _getter.__name__ = name                                                                       │
│   102 │   │   │   _setter.__name__ = name                                                                       │
│                                                                                                                 │
│ c:\Users\Knollr\Documents\github_ehrapy\.venv\Lib\site-packages\pandas\core\arrays\categorical.py:2460 in       │
│ _delegate_property_set                                                                                          │
│                                                                                                                 │
│   2457 │   │   return getattr(self._parent, name)                                                               │
│   2458 │                                                                                                        │
│   2459 │   def _delegate_property_set(self, name, new_values):                                                  │
│ ❱ 2460 │   │   return setattr(self._parent, name, new_values)                                                   │
│   2461 │                                                                                                        │
│   2462 │   @property                                                                                            │
│   2463 │   def codes(self) -> Series:                                                                           │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: property 'categories' of 'Categorical' object has no setter
```

#### Versions:

> cellrank==2.0.0 scanpy==1.9.3 anndata==0.9.1 numpy==1.24.3 numba==0.57.1 scipy==1.11.0 pandas==2.0.2 pygpcca==1.0.4 scikit-learn==1.2.2 statsmodels==0.14.0 python-igraph==0.10.4 scvelo==0.2.5 pygam==0.8.0 matplotlib==3.7.1 seaborn==0.12.2

**Comment by knollr** [comment]
Ok using pandas < 2.0.0 solved the issue.

**Comment by Marius1311** [comment]
@michalk8, would still be good to fix this, users should not have to downgrade pandas here.

**Comment by michalk8** [comment]
This is an `scvelo` issue, should be fixed there.

**Comment by Marius1311** [comment]
Ah, is it fixed on scVelo's main already?

**Comment by joaoufrj** [comment]
I downgraded to pandas 1.3.5 because of a similar issue when using scVelo and I still get this error with cellrank 2.0

**Comment by joaoufrj** [comment]
I installed the dev version of CellRank (v2.0.1) and pandas 1.5.3 and now plotting works fine.
