### ISSUE TITLE
Conda installs incompatible numba version

### ISSUE THREAD

**Issue by WeilerP** [theislab/cellrank#593]
Using `conda install -c conda-forge -c bioconda cellrank`, an incompatible version of `numba` (see e.g. theislab/scanpy#1756 or theislab/scvelo#387) is installed. The problem should be [this](https://github.com/bioconda/bioconda-recipes/blob/a8d6f606b3d828153571f4bcc06f768af59e452d/recipes/cellrank/meta.yaml#L31) line.

**Comment by WeilerP** [comment]
I opened bioconda/bioconda-recipes#28591 which should fix it.

**Comment by Marius1311** [comment]
Hi @WeilerP, has this been solved?

**Comment by WeilerP** [comment]
No, unfortunately, not yet. Decided to close `bioconda/bioconda-recipes#28591` and resolve it through `scanpy` instead (see `theislab/scanpy#1756`. This is an ongoing discussion, though.

**Comment by Marius1311** [comment]
Can you post a link to the issue please?

**Comment by WeilerP** [comment]
> Can you post a link to the issue please?

Oups, sorry, I fixed the [original comment](https://github.com/theislab/cellrank/issues/593#issuecomment-847853514) above to point to the issues.

**Comment by Marius1311** [comment]
Ok, thanks for taking care of this!

**Comment by WeilerP** [comment]
Just in case someone is coming across the same issue: The problem can be fixed by first installing a compatible `numba` version using conda and then `cellrank` afterwards.

**Comment by Marius1311** [comment]
@WeilerP, can this be closed?

**Comment by WeilerP** [comment]
No, sorry, it's still ongoing. I'm still waiting to release the new scvelo version.

**Comment by Marius1311** [comment]
Okay, got it.

**Comment by michalk8** [comment]
solved via https://github.com/theislab/cellrank/issues/650

**Comment by WeilerP** [comment]
@michalk8, is still really solved? Doesn't the issue persist because of `scvelo`?

**Comment by michalk8** [comment]
> @michalk8, is still really solved? Doesn't the issue persist because of scvelo?

The underlying issue should be solved (it's the same as installing through `pip`) - in CellRank's `meta.yml` file, there was no upper bound pin for `numba` and `scvelo` pins `umap-learn` from above, which doesn't work with newer numba versions.

**Comment by WeilerP** [comment]
> > @michalk8, is still really solved? Doesn't the issue persist because of scvelo?
> 
> The underlying issue should be solved (it's the same as installing through `pip`) - in CellRank's `meta.yml` file, there was no upper bound pin for `numba` and `scvelo` pins `umap-learn` from above, which doesn't work with newer numba versions.

Yes, sorry, my bad. I thought the upper bound on `numba` was removed but it was actually added it. 👍 . I'll let you know once the new `scvelo` version has been released.
