### ISSUE TITLE
Transition matrix is not row-stochastic.

### ISSUE THREAD

**Issue by haikuol** [theislab/cellrank#652]
...
Hello!

I am following the tutorial of Time series datasets on my own dataset. I did everything on the basis of X_umap instead of force_directed.
But I got the following error when running wk.plot_random_walks. Do you have any thoughts? Thanks in advance!

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-48-849fcbf4d55f> in <module>
----> 1 wk.plot_random_walks(
      2     n_sims=300,
      3     max_iter=200,
      4     start_ixs={"day": 0},
      5     basis="umap",

~/anaconda3/lib/python3.8/site-packages/cellrank/tl/kernels/_base_kernel.py in plot_random_walks(self, n_sims, max_iter, seed, successive_hits, start_ixs, stop_ixs, basis, cmap, linewidth, linealpha, ixs_legend_loc, n_jobs, backend, show_progress_bar, figsize, dpi, save, **kwargs)
    443         start_ixs = create_ixs(start_ixs, kind="start")
    444         stop_ixs = create_ixs(stop_ixs, kind="stop")
--> 445         rw = RandomWalk(self.transition_matrix, start_ixs=start_ixs, stop_ixs=stop_ixs)
    446         sims = rw.simulate_many(
    447             n_sims=n_sims,

~/anaconda3/lib/python3.8/site-packages/cellrank/tl/kernels/_random_walk.py in __init__(self, transition_matrix, start_ixs, stop_ixs)
     35             raise ValueError("Array is not a square matrix.")
     36         if not np.allclose(transition_matrix.sum(1), 1.0):
---> 37             raise ValueError("Transition matrix is not row-stochastic.")
     38 
     39         self._tmat = transition_matrix

ValueError: Transition matrix is not row-stochastic.

**Comment by haikuol** [comment]
This is what I got from wk.compute_transition_matrix( growth_iters=3, growth_rate_key="growth_rate_init", last_time_point="connectivities"):


Computing transition matrix using Waddington optimal transport
Using `2684` HVGs from `adata.var['highly_variable']`
Using default cost matrices
Computing transport maps for `5` time pairs
100%
5/5 [08:06<00:00, 99.77s/time pair]
    Finish (0:08:06)
computing neighbors
    using 'X_pca' with n_pcs = 50
    finished: added to `.uns['neighbors']`
    `.obsp['distances']`, distances for each pair of neighbors
    `.obsp['connectivities']`, weighted adjacency matrix (0:00:13)
Computing transition matrix based on `adata.obsp['connectivities']`
    Finish (0:00:00)
    Finish (0:08:35)

**Comment by michalk8** [comment]
Hi @haikuol ,

seems like some rows of the transition matrix do not sum to 1 within the default tolerance, could you try running:
```python
mask = ~np.isclose(wk.transition_matrix.sum(1), 1.0)
print(np.isinf(wk.transition_matrix.data).any())
print(np.isnan(wk.transition_matrix.data).any())
print(np.sum(mask))
if np.sum(mask):
    print(wk.transition_matrix[mask, :].sum(1))
```
to further see how large the deviation is? My suspicion is that either it's just large enough above the default threshold even after normalization or that some +/- inf values have crept in the transport map calcuation (currently, we only check for NaNs).

Just noticed the transport maps from WOT are stored as `float32`, will make a PR to store them as `float64`.
I've also rerun the tutorial - I assume you've somehow subsetted the data because I see
"Computing transport maps for 5 time pairs", whereas in the tutorial, there are `38` time pairs - so I did it as 
```python
adata = adata[adata.obs['day'].isin(adata.obs['day'].cat.categories[:6])].copy()
```
and unfortunately, I can't reproduce this locally.

**Comment by haikuol** [comment]
> Hi @haikuol ,
> 
> seems like some rows of the transition matrix do not sum to 1 within the default tolerance, could you try running:
> 
> ```python
> import numpy as np
> 
> mask = ~np.isclose(wk.transition_matrix.sum(1), 1.0)
> print(np.isinf(wk.transition_matrix.data).any())
> print(np.isnan(wk.transition_matrix.data).any())
> print(np.sum(mask))
> if np.sum(mask):
>     print(wk.transition_matrix[mask, :].sum(1))
> ```
> 
> to further see how large the deviation is? My suspicion is that either it's just large enough above the default threshold even after normalization or that some +/- inf values have crept in the transport map calcuation (currently, we only check for NaNs).
> 
> Just noticed the transport maps from WOT are stored as `float32`, will make a PR to store them as `float64`.
> I've also rerun the tutorial - I assume you've somehow subsetted the data because I see
> "Computing transport maps for 5 time pairs", whereas in the tutorial, there are `38` time pairs - so I did it as
> 
> ```python
> adata = adata[adata.obs['day'].isin(adata.obs['day'].cat.categories[:6])].copy()
> ```
> 
> and unfortunately, I can't reproduce this locally.

**Comment by haikuol** [comment]
@michalk8 Thanks for your quick response!

I got the following by running:

mask = ~np.isclose(wk.transition_matrix.sum(1), 1.0)
print(np.isinf(wk.transition_matrix.data).any())
print(np.isnan(wk.transition_matrix.data).any())
print(np.sum(mask))
if np.sum(mask):
    print(wk.transition_matrix[mask, :].sum(1))



False
False
1
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-25-33b3329d6dfa> in <module>
      4 print(np.sum(mask))
      5 if np.sum(mask):
----> 6     print(wk.transition_matrix[mask, :].sum(1))

~/anaconda3/lib/python3.8/site-packages/scipy/sparse/_index.py in __getitem__(self, key)
     31     """
     32     def __getitem__(self, key):
---> 33         row, col = self._validate_indices(key)
     34         # Dispatch to specialized methods.
     35         if isinstance(row, INT_TYPES):

~/anaconda3/lib/python3.8/site-packages/scipy/sparse/_index.py in _validate_indices(self, key)
    127     def _validate_indices(self, key):
    128         M, N = self.shape
--> 129         row, col = _unpack_index(key)
    130 
    131         if isintlike(row):

~/anaconda3/lib/python3.8/site-packages/scipy/sparse/_index.py in _unpack_index(index)
    284     bool_col = _compatible_boolean_index(col)
    285     if bool_row is not None:
--> 286         row = _boolean_index_to_array(bool_row)
    287     if bool_col is not None:
    288         col = _boolean_index_to_array(bool_col)

~/anaconda3/lib/python3.8/site-packages/scipy/sparse/_index.py in _boolean_index_to_array(idx)
    365 def _boolean_index_to_array(idx):
    366     if idx.ndim > 1:
--> 367         raise IndexError('invalid index shape')
    368     return np.where(idx)[0]

IndexError: invalid index shape





As mentioned, I was not using the dataset in the tutorial. I am glad to send you my anndata if you need to reproduce it.

**Comment by michalk8** [comment]
Based on the above, thare are no NaN or infs in the transition matrix, which is great and that there's only 1 row
where the values don't sum to 1. Unfortunately, I've made a typo in the aove, could you just run this?
```python
mask = np.asarray(~np.isclose(wk.transition_matrix.sum(1), 1.0)).squeeze()
if np.sum(mask):
    print(wk.transition_matrix[mask, :].sum(1))
    print(wk.transition_matrix[mask, :].data)
```
2 things can happen:
- problems with the precision: should be fixed by #653
 (you can try to install the update version as `pip install git+https://github.com/theislab/cellrank@dev`
- all the values are 0: my hunch tells me it can happen because the growth rate for the 1 cell is 0, but am not sure

**Comment by haikuol** [comment]
> Based on the above, thare are no NaN or infs in the transition matrix, which is great and that there's only 1 row
> where the values don't sum to 1. Unfortunately, I've made a typo in the aove, could you just run this?
> 
> ```python
> mask = np.asarray(~np.isclose(wk.transition_matrix.sum(1), 1.0)).squeeze()
> if np.sum(mask):
>     print(wk.transition_matrix[mask, :].sum(1))
>     print(wk.transition_matrix[mask, :].data)
> ```
> 
> 2 things can happen:
> 
> * problems with the precision: should be fixed by [Transport maps as f64, enable WOT on CI #653](https://github.com/theislab/cellrank/pull/653)
>   (you can try to install the update version as `pip install git+https://github.com/theislab/cellrank@dev`
> * all the values are 0: my hunch tells me it can happen because the growth rate for the 1 cell is 0, but am not sure

Sounds great! I got these two values:

[[7.12968047e-16]]
[7.12968047e-16]

How to interpret them please?
Has it already been fixed in the updated version or when will it be fixed? Thanks again!

**Comment by michalk8** [comment]
>  Has it already been fixed in the updated version or when will it be fixed? Thanks again!

I think the problem was that we had some small constant `eps` to avoid division by zero when row-normalizing the values, which could've caused this - I've issued a fix right now, you could try it by installing the `dev` as mentioned above.

> How to interpret them please?

Without knowing the scale of other values in the transport maps, it's hard pin it down:
- if all the values similarly small, it could just mean that this particular cell distributes its mass only to 1 cell and we failed to normalize this row to 1 because of the `eps`
- could also be something else (almost failed convergence?), will discuss with @Marius1311 later

**Comment by michalk8** [comment]
@haikuol does the error still persist when you install from `dev`?

**Comment by haikuol** [comment]
> @haikuol does the error still persist when you install from `dev`?

I think it works well now. Thanks for your help!

**Comment by michalk8** [comment]
> I think it works well now. Thanks for your help!

Glad that it works. Closing this.
